
CREATE DATABASE Search_PHP;
USE             Search_PHP;

CREATE TABLE Users (
    UserId       INT         NOT NULL PRIMARY KEY AUTO_INCREMENT,
    UserName     VARCHAR(60) NOT NULL,
    UserUsername VARCHAR(60) NOT NULL UNIQUE
);

INSERT INTO Users VALUES
(null, 'Warren Buffett',               'warrenbuffett'),
(null, 'Elon Musk',                    'elonmusk'),
(null, 'Jeff Bezos',                   'jeffbezos'),
(null, 'Bernard Arnault',              'bernardarnault'),
(null, 'Bill Gates',                   'billgates'),
(null, 'Mark Zuckerberg',              'zuck'),
(null, 'Larry Page',                   'larrypage'),
(null, 'Sergey Brin',                  'sergeybrin'),
(null, 'Amancio Ortega',               'amancioortega'),
(null, 'Carlos Slim',                  'carlosslim'),
(null, 'Francoise Bettencourt Meyers', 'francoisebettencourt'),
(null, 'Mukesh Ambani',                'mukeshambani'),
(null, 'Elon Ries',                    'elonries'),
(null, 'Oprah Winfrey',                'oprahwinfrey'),
(null, 'Aliko Dangote',                'alikodangote'),
(null, 'Jack Ma',                      'jackma'),
(null, 'Alice Walton',                 'alicewalton'),
(null, 'Jim Walton',                   'jimwalton'),
(null, 'Rob Walton',                   'robwalton'),
(null, 'Ma Huateng',                   'mahuateng'),
(null, 'Sheldon Adelson',              'sheldonadelson'),
(null, 'Michael Bloomberg',            'michaelbloomberg'),
(null, 'Warren Walton',                'warrenwalton'),
(null, 'Charles Koch',                 'charleskoch'),
(null, 'David Koch',                   'davidkoch'),
(null, 'S. Robson Walton',             'srobsonwalton'),
(null, 'Elaine Marshall',              'elainemarshall'),
(null, 'Susanne Klatten',              'susanneklatten'),
(null, 'Stefan Quandt',                'stefanquandt'),
(null, 'Li Ka-shing',                  'likashing'),
(null, 'Jacqueline Mars',              'jacquelinemars'),
(null, 'John Mars',                    'johnmars'),
(null, 'Richard Branson',              'richardbranson'),
(null, 'George Soros',                 'georgesoros'),
(null, 'Warren Buffet Jr.',            'warrenbuffetjr'),
(null, 'Abigail Johnson',              'abigailjohnson'),
(null, 'Larry Ellison',                'larryellison'),
(null, 'George Lucas',                 'georgelucas'),
(null, 'Micky Arison',                 'mickyarison'),
(null, 'J.K. Rowling',                 'jkrowling'),
(null, 'Michael Jordan',               'michaeljordan'),
(null, 'George Clooney',               'georgeclooney'),
(null, 'Beyoncé Knowles',              'beyonceknowles'),
(null, 'Kylie Jenner',                 'kyliejenner'),
(null, 'Taylor Swift',                 'taylorswift'),
(null, 'Kim Kardashian',               'kimkardashian'),
(null, 'Jay-Z',                        'jayz'),
(null, 'Kanye West',                   'kanyewest'),
(null, 'Ellen DeGeneres',              'ellendegeneres'),
(null, 'Roger Federer',                'rogerfederer'),
(null, 'Serena Williams',              'serenawilliams'),
(null, 'Cristiano Ronaldo',            'cristianoronaldo'),
(null, 'Lionel Messi',                 'lionelmessi'),
(null, 'Richard Li',                   'richardli'),
(null, 'Hui Ka Yan',                   'huikayan'),
(null, 'Pony Ma',                      'ponyma'),
(null, 'Li Shufu',                     'lishufu'),
(null, 'William Ding',                 'williamding'),
(null, 'Robin Li',                     'robinli'),
(null, 'Vladimir Putin',               'vladimirputin'),
(null, 'Xi Jinping',                   'xijinping'),
(null, 'Angela Merkel',                'angelamerkel'),
(null, 'Emmanuel Macron',              'emmanuelmacron'),
(null, 'Justin Trudeau',               'justintrudeau'),
(null, 'Narendra Modi',                'narendramodi'),
(null, 'Shinzo Abe',                   'shinzoabe'),
(null, 'Jacinda Ardern',               'jacindaardern'),
(null, 'Queen Elizabeth II',           'queenelizabeth'),
(null, 'Pope Francis',                 'popefrancis');

SELECT * FROM Users;
